#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# migrations are now handled by entrypoint of production
# python manage.py migrate
uvicorn config.asgi:application --host 0.0.0.0 --reload
