# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_keyvaluesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='titleslug',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='keyvaluesetting',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
