# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170305_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_only',
            field=models.BooleanField(default=False),
        ),
    ]
