# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_audio_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='titleslug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
