# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170307_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extract_audio',
            field=models.BooleanField(default=False),
        ),
    ]
